derhks_polls/derhks_polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),  # Primer argumento la ruta, segundo argumento la vista
]

derhks_polls/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ejemplo: /polls/
    path('', views.index, name='index'),
    # ejemplo: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ejemplo: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ejemplo: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('create_question/', views.CreateQuestion.as_view(), name='create_question'),
    path('create_choice/', views.CreateChoice.as_view(), name='create_choice'),
]

derhks_polls/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

derhks_polls/polls/forms.py
from django import forms

from .models import Question, Choice


class QuestionForm(forms.ModelForm):  # Se utiliza la clase ModelForm ya que el formulario se va a basar en un modelo

    class Meta:
        model = Question
        fields = '__all__'  # Uso __all__ para renderizar todos los atributos del modelo


class ChoicesForm(forms.ModelForm):

    class Meta:
        model = Choice
        fields = ('question', 'choice_text')

derhks_polls/polls/views.py
from django.shortcuts import render

from django.db.models import F
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView

from .models import Question, Choice
from .forms import QuestionForm, ChoicesForm


def index(request):
    latest_question_list = Question.objects.filter(
        pub_date__lte=timezone.now()
    ).order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }

    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    try:
        question = Question.objects.filter(
            pub_date__lte=timezone.now()
        ).get(pk=question_id)
        context = {
            'question': question,
        }
    except Question.DoesNotExist:
        raise Http404("Question does not exist")

    return render(request, 'polls/detail.html', context)


def results(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
        context = {
            'question': question
        }
    except Question.DoesNotExist:
        raise Http404("Question does not exist")

    return render(request, 'polls/results.html', context)


def vote(request, question_id):
    context = {}

    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        context['question'] = question
        context['error_message'] = "You didn't select a choice"

        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', context)
    else:
        selected_choice.votes = F('votes') + 1  # F elimina la condicion de carrera
        selected_choice.save()

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class CreateQuestion(CreateView):
    model = Question
    form_class = QuestionForm
    template_name = 'create_question.html'
    success_url = reverse_lazy('polls:index')


class CreateChoice(CreateView):
    model = Choice
    form_class = ChoicesForm
    template_name = 'create_choice.html'
    success_url = reverse_lazy('polls:index')

derhks_polls/polls/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            {% block title %}
                Derhks Polls
            {% endblock title %}
        </title>
        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="nav-link" aria-current="page" href="{% url 'polls:index' %}">Home</a>
            <a class="nav-link" href="{% url 'polls:create_question' %}">Create Question</a>
            <a class="nav-link" href="{% url 'polls:create_choice' %}">Create Choice</a>
        </nav>

        {% block content %}
        {% endblock content %}

    </body>
</html>

derhks_polls/polls/templates/create_choice.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %}
    Create Choice
{% endblock title %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'create_question.css' %}">

    <form method="post">
        <div class="form-group">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="button" type="submit" value="Create"/>
        </div>
    </form>
{% endblock content %}

derhks_polls/polls/templates/create_question.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %}
    Create Question
{% endblock title %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'create_question.css' %}">

    <form method="post">
        <div class="form-group">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="button" value="Create"/>
        </div>
    </form>
{% endblock content %}

derhks_polls/polls/templates/polls/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/detail_style.css' %}">

    <div>
        <h1>{{ question.question_text }}</h1>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <input type="checkbox" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
            <input type="submit" value="Vote">
        </form>
    </div>
{% endblock content %}

derhks_polls/polls/templates/polls/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/index_style.css' %}">

    <h1>Questions List</h1>

    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li>
                    <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock content %}

derhks_polls/polls/templates/polls/results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/results_style.css' %}">

    <div>
        <h1>{{ question.question_text }}</h1>

        <ul>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
            {% endfor %}
        </ul>

        <button role="link" onclick="window.location='{% url 'polls:detail' question.id %}'">Vote again?</button>
    </div>
{% endblock content %}